server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud 게이트웨이 글로벌 필터
            preLogger: true
            postLogger: true

      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
          filters:
            - AddRequestHeader=first-request, this-is-header-value-1
            - AddResponseHeader=first-response, this-is-header-value-1
            - CustomFilter
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-request, this-is-header-value-2
            - AddResponseHeader=second-response, this-is-header-value-2
            - CustomFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false

